### ISSUE TITLE
leaderboardQuery.set_skip_result_to_rank uses "true" instead of an integer.

### ISSUE THREAD

**Issue by RustyMoyher** [Microsoft/xbox-live-samples#55]
On line 74 inside of StatsManagerIntegration.cpp, leaderboardQuery.set_skip_result_to_rank uses "true" instead of an integer.

Should probably be leaderboardQuery.set_skip_result_to_rank(10); or something.

**Comment by jasonsandlin** [comment]
Good catch, thanks.  Fixed
